files:
  - source: /content/en/docs/*.md
    translation: /content/%locale%/docs/%original_file_name%
  - source: /content/en/docs/development/*.md
    translation: /content/%locale%/docs/development/%original_file_name%
